/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BigSmallPrediction {
  'prediction' : string,
  'explanation' : string,
}
export interface HistoryItem { 'result' : string, 'timestamp' : bigint }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'analyzeBias' : ActorMethod<[Array<HistoryItem>], [bigint, bigint]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHistory' : ActorMethod<[], Array<HistoryItem>>,
  'getPrediction' : ActorMethod<[Array<HistoryItem>], BigSmallPrediction>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'historicalPatternAnalysis' : ActorMethod<
    [Array<HistoryItem>],
    Array<Array<string>>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveHistoryEntry' : ActorMethod<[HistoryItem], undefined>,
  'switchTrendAnalysis' : ActorMethod<[Array<HistoryItem>], [boolean, bigint]>,
  'updatePredictionFeedback' : ActorMethod<[Array<boolean>], undefined>,
  'updateTimeWindow' : ActorMethod<[bigint], undefined>,
  'uploadHistoricalPatterns' : ActorMethod<[Array<Array<string>>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];