/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HistoryItem = IDL.Record({
  'result' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const BigSmallPrediction = IDL.Record({
  'prediction' : IDL.Text,
  'explanation' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'analyzeBias' : IDL.Func([IDL.Vec(HistoryItem)], [IDL.Nat, IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(HistoryItem)], ['query']),
  'getPrediction' : IDL.Func(
      [IDL.Vec(HistoryItem)],
      [BigSmallPrediction],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'historicalPatternAnalysis' : IDL.Func(
      [IDL.Vec(HistoryItem)],
      [IDL.Vec(IDL.Vec(IDL.Text))],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveHistoryEntry' : IDL.Func([HistoryItem], [], []),
  'switchTrendAnalysis' : IDL.Func(
      [IDL.Vec(HistoryItem)],
      [IDL.Bool, IDL.Nat],
      ['query'],
    ),
  'updatePredictionFeedback' : IDL.Func([IDL.Vec(IDL.Bool)], [], []),
  'updateTimeWindow' : IDL.Func([IDL.Int], [], []),
  'uploadHistoricalPatterns' : IDL.Func([IDL.Vec(IDL.Vec(IDL.Text))], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HistoryItem = IDL.Record({
    'result' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const BigSmallPrediction = IDL.Record({
    'prediction' : IDL.Text,
    'explanation' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'analyzeBias' : IDL.Func([IDL.Vec(HistoryItem)], [IDL.Nat, IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHistory' : IDL.Func([], [IDL.Vec(HistoryItem)], ['query']),
    'getPrediction' : IDL.Func(
        [IDL.Vec(HistoryItem)],
        [BigSmallPrediction],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'historicalPatternAnalysis' : IDL.Func(
        [IDL.Vec(HistoryItem)],
        [IDL.Vec(IDL.Vec(IDL.Text))],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveHistoryEntry' : IDL.Func([HistoryItem], [], []),
    'switchTrendAnalysis' : IDL.Func(
        [IDL.Vec(HistoryItem)],
        [IDL.Bool, IDL.Nat],
        ['query'],
      ),
    'updatePredictionFeedback' : IDL.Func([IDL.Vec(IDL.Bool)], [], []),
    'updateTimeWindow' : IDL.Func([IDL.Int], [], []),
    'uploadHistoricalPatterns' : IDL.Func([IDL.Vec(IDL.Vec(IDL.Text))], [], []),
  });
};

export const init = ({ IDL }) => { return []; };